[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    '@layerzero-v2/=lib/LayerZero-v2/packages/layerzero-v2/',
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzero-devtools/=lib/devtools/packages/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
    'forge-std/=lib/forge-std/src/'
]

[rpc_endpoints]
base_mainnet="wss://base-rpc.publicnode.com"
hyperliquid_mainnet="https://rpc.hyperliquid.xyz/evm"
arb_mainnet="https://lb.drpc.live/arbitrum/AoOdvxG5CECfnucrC7m69zQ8-dbSqXoR8LgRQrxF2MGT"

[lint]
exclude_lints = ["unsafe-typecast", "mixed-case-variable"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
